Repository jbaublitz/neli, pull requests merged in 2021-02, with the labels that each got.

#127 Add Ndmsg::new function to initialize Ndmsg
  src/rtnl.rs
Labels: bug

#128 Fix clippy
  .github/workflows/main.yml
Labels: ci

#130 Add iter2()
  src/socket.rs
Labels: enhancement

#131 Fix bug in Ifinfomsg
  src/rtnl.rs
Labels: bug

#132 Add methods to get AttrHandle and AttrHandleMut data structures
  src/genl.rs
  src/types.rs
Labels: enhancement
