Repository jbaublitz/neli, pull requests merged in 2025-06, with the labels that each got.

#280 Pass full io::Error to user
  src/err.rs
Labels: enhancement

#278 Fix rta deserialization test for big endian
  src/rtnl.rs
Labels: bug, testing

#279 Directly implement FromBytesWithInput and ToBytes for Buffer
  src/types.rs
Labels: enhancement

#282 Fix bug in group handling with getsockopt syscall
  src/socket/shared.rs
Labels: bug

#284 Release of neli-v0.7.0 and neli-proc-macros-v0.2.0
  CHANGELOG.md
  Cargo.toml
  README.md
  neli-proc-macros/Cargo.toml
Labels: release

#285 Update env_logger
  Cargo.toml
Labels: maintenance

#286 Update to Rust edition 2024
  Cargo.toml
  examples/create-nested-attributes.rs
  neli-proc-macros/Cargo.toml
  neli-proc-macros/src/derive_frombytes.rs
  neli-proc-macros/src/derive_header.rs
  neli-proc-macros/src/derive_size.rs
  neli-proc-macros/src/derive_tobytes.rs
  neli-proc-macros/src/lib.rs
  neli-proc-macros/src/neli_enum.rs
  neli-proc-macros/src/shared.rs
  src/attr.rs
  src/consts/genl.rs
  src/err.rs
  src/genl.rs
  src/iter.rs
  src/lib.rs
  src/nl.rs
  src/router/asynchronous.rs
  src/router/synchronous.rs
  src/rtnl.rs
  src/socket/asynchronous.rs
  src/socket/shared.rs
  src/socket/synchronous.rs
  src/types.rs
Labels: maintenance
