Repository jbaublitz/neli, pull requests merged in 2025-07, with the labels that each got.

#288 Add option to set recv buffer size
  src/socket/asynchronous.rs
  src/socket/shared.rs
  src/socket/synchronous.rs
Labels: enhancement

#293 Optionally get the buffer for deserialization, avoiding panic if index is out of bounds
  .github/workflows/main.yml
  neli-proc-macros/src/derive_frombytes.rs
Labels: bug

#290 Expand nl80211 example
  examples/nl80211.rs
Labels: enhancement, documentation
